"""add otp_challenge

Revision ID: 630fa127b744
Revises: 642d738f82e4
Create Date: 2026-07-04 02:41:44.659986
"""
from alembic import op
import sqlalchemy as sa


revision = '630fa127b744'
down_revision = '642d738f82e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_challenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenge_participant_id'), ['participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenge_participant_id'))

    op.drop_table('otp_challenge')
    # ### end Alembic commands ###
