"""initial schema

Revision ID: 642d738f82e4
Revises: 
Create Date: 2026-07-03 16:24:43.104820
"""
from alembic import op
import sqlalchemy as sa

revision = '642d738f82e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_protocol',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('protocol_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('band', sa.String(length=8), nullable=False),
    sa.Column('carrier_hz', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('beat_hz', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('duration_s', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('target_peak_dbfs', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("band in ('alpha','theta','delta')", name='ck_protocol_band'),
    sa.CheckConstraint('carrier_hz > 0 and duration_s > 0', name='ck_protocol_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'version', name='uq_protocol_version')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), server_default=sa.text("'active'"), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('active','withdrawn','completed')", name='ck_participant_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_code')
    )
    op.create_table('staff_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('mfa_secret', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role in ('researcher','admin')", name='ck_staff_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('allocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('arm_coded', sa.String(length=1), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('sequence_seed_ref', sa.String(length=64), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unblinded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("arm_coded in ('A','B')", name='ck_allocation_arm'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', name='uq_allocation_participant')
    )
    with op.batch_alter_table('allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_participant_id'), ['participant_id'], unique=False)

    op.create_table('baseline_assessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('gad7_items', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False),
    sa.Column('gad7_total', sa.SmallInteger(), nullable=False),
    sa.Column('psqi_input', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False),
    sa.Column('psqi_global', sa.SmallInteger(), nullable=False),
    sa.Column('score_version', sa.String(length=20), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('gad7_total between 0 and 21', name='ck_baseline_gad7'),
    sa.CheckConstraint('psqi_global between 0 and 21', name='ck_baseline_psqi'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline_assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_assessment_participant_id'), ['participant_id'], unique=False)

    op.create_table('consent_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('tcle_version', sa.String(length=20), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45).with_variant(sa.String(length=45), 'postgresql'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_record_participant_id'), ['participant_id'], unique=False)

    op.create_table('contact_info',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('enc_name', sa.LargeBinary(), nullable=False),
    sa.Column('enc_email', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', name='uq_contact_participant')
    )
    with op.batch_alter_table('contact_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_info_participant_id'), ['participant_id'], unique=False)

    op.create_table('followup_assessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('gad7_total', sa.SmallInteger(), nullable=False),
    sa.Column('psqi_global', sa.SmallInteger(), nullable=False),
    sa.Column('sus_score', sa.SmallInteger(), nullable=False),
    sa.Column('blinding_guess', sa.String(length=8), nullable=True),
    sa.Column('score_version', sa.String(length=20), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("blinding_guess in ('A','B','nao_sei') or blinding_guess is null", name='ck_follow_guess'),
    sa.CheckConstraint('gad7_total between 0 and 21', name='ck_follow_gad7'),
    sa.CheckConstraint('psqi_global between 0 and 21', name='ck_follow_psqi'),
    sa.CheckConstraint('sus_score between 0 and 100', name='ck_follow_sus'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followup_assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followup_assessment_participant_id'), ['participant_id'], unique=False)

    op.create_table('screening',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('criteria', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False),
    sa.Column('symptoms', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screening', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_participant_id'), ['participant_id'], unique=False)

    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_uuid', sa.Uuid(), nullable=False),
    sa.Column('protocol_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_seconds', sa.Integer(), nullable=True),
    sa.Column('interruptions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('headphones_ok', sa.Boolean(), nullable=False),
    sa.Column('device_info', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_uuid'], ['audio_protocol.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_protocol_uuid'), ['protocol_uuid'], unique=False)

    op.create_table('sleep_diary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('diary_date', sa.Date(), nullable=False),
    sa.Column('latency_min', sa.Integer(), nullable=True),
    sa.Column('awakenings', sa.Integer(), nullable=True),
    sa.Column('duration_h', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('quality', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'diary_date', name='uq_diary_day')
    )
    with op.batch_alter_table('sleep_diary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_diary_participant_id'), ['participant_id'], unique=False)

    op.create_table('adverse_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('outcome', sa.String(length=200), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity in ('mild','moderate','severe')", name='ck_ae_severity'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adverse_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adverse_event_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_event_session_id'), ['session_id'], unique=False)

    op.create_table('post_session_survey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('feeling', sa.SmallInteger(), nullable=False),
    sa.Column('relaxation', sa.SmallInteger(), nullable=False),
    sa.Column('slept_better', sa.SmallInteger(), nullable=True),
    sa.Column('liked', sa.SmallInteger(), nullable=False),
    sa.Column('intensity', sa.SmallInteger(), nullable=False),
    sa.Column('would_repeat', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('feeling between 0 and 4 and relaxation between 0 and 4 and liked between 0 and 4 and intensity between 0 and 4', name='ck_survey_scales'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_survey_session')
    )
    with op.batch_alter_table('post_session_survey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_session_survey_session_id'), ['session_id'], unique=False)

    op.create_table('recommendation_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('inputs', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False),
    sa.Column('rule_id', sa.String(length=40), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('suggested_protocol', sa.String(length=40), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_log_participant_id'), ['participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_log_participant_id'))

    op.drop_table('recommendation_log')
    with op.batch_alter_table('post_session_survey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_session_survey_session_id'))

    op.drop_table('post_session_survey')
    with op.batch_alter_table('adverse_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adverse_event_session_id'))
        batch_op.drop_index(batch_op.f('ix_adverse_event_participant_id'))

    op.drop_table('adverse_event')
    with op.batch_alter_table('sleep_diary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_diary_participant_id'))

    op.drop_table('sleep_diary')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_protocol_uuid'))
        batch_op.drop_index(batch_op.f('ix_session_participant_id'))

    op.drop_table('session')
    with op.batch_alter_table('screening', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_participant_id'))

    op.drop_table('screening')
    with op.batch_alter_table('followup_assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followup_assessment_participant_id'))

    op.drop_table('followup_assessment')
    with op.batch_alter_table('contact_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_info_participant_id'))

    op.drop_table('contact_info')
    with op.batch_alter_table('consent_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_record_participant_id'))

    op.drop_table('consent_record')
    with op.batch_alter_table('baseline_assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_assessment_participant_id'))

    op.drop_table('baseline_assessment')
    with op.batch_alter_table('allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_participant_id'))

    op.drop_table('allocation')
    op.drop_table('staff_user')
    op.drop_table('participant')
    op.drop_table('audit_log')
    op.drop_table('audio_protocol')
    # ### end Alembic commands ###
