"""followup raw items and numeric sus

Revision ID: 90dacb6be54c
Revises: 630fa127b744
Create Date: 2026-07-04 02:53:38.394742
"""
from alembic import op
import sqlalchemy as sa

revision = '90dacb6be54c'
down_revision = '630fa127b744'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followup_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gad7_items', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('psqi_input', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('sus_items', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False))
        batch_op.alter_column('sus_score',
               existing_type=sa.SMALLINT(),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followup_assessment', schema=None) as batch_op:
        batch_op.alter_column('sus_score',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.SMALLINT(),
               existing_nullable=False)
        batch_op.drop_column('sus_items')
        batch_op.drop_column('psqi_input')
        batch_op.drop_column('gad7_items')

    # ### end Alembic commands ###
